# 端口号
server:
  port: 8007


# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'


# Nacos
spring:
  application:
    name: shopping_seckill_customer_api
  cloud:
    sentinel:
      transport:
        # Sentinel 控制台地址
        dashboard: 192.168.44.100:8899
    nacos:
      discovery:
        server-addr: 192.168.44.100:8848


dubbo:
  application:
    #项目名字
    name: shopping_seckill_customer_api
  protocol:
    name: dubbo
    port: -1
  registry:
    # 注册地址
    address: nacos://192.168.44.100:8848

