# 端口号
server:
  port: 9001


# 日志格式
logging:
  pattern:
    console: '%d{HH:mm:ss.SSS} %clr(%-5level) ---  [%-15thread] %cyan(%-50logger{50}):%msg%n'


spring:
  application:
    name: shopping_goods_service #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.44.135:8848 # 注册中心地址
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.44.134:3312/shopping?serverTimezone=UTC
    username: root
    password: 123456


dubbo:
  application:
    name: shopping_goods_service #服务名
    qos-enable: false
    serialize-check-status: DISABLE
    check-serializable: false
  consumer:
    timeout: 5000
  protocol:
    name: dubbo # 通讯协议
    port: -1 # 端口号，-1表示自动扫描可用端口。
  registry:
    address: nacos://192.168.44.135:8848 # 注册中心



# 配置Mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      # 表名前缀
      table-prefix: t_
      # 主键生成策略为自增
      id-type: auto
  configuration:
    # 关闭列名自动驼峰命名映射规则
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
